language: r
cache: packages
warnings_are_errors: false
addons:
  apt:
    packages:
    - unixodbc-dev
    - libcurl4-openssl-dev
    - texlive-full
r_github_packages:
  - lockedata/revealjs
  - stephlocke/stephStyle
after_success:
  - R CMD build .
  - Rscript -e 'devtools::install(pkg = ".")'
  - Rscript -e 'devtools::install_github("stephlocke/tfsR",dependencies=TRUE)'
  - chmod 755 .push_gh_pages.sh
  - chmod 755 ghgenerate.R
  - ./.push_gh_pages.sh
